### ISSUE TITLE
Notification regression

### ISSUE THREAD

**Issue by SZenglein** [LibreShift/red-moon#209]
Hey, I'm currently still on version 3.0 since in my opinion the notification in newer versions is a regression. It doesn't show the current profile anymore. It permanently shows the warning to disable red moon to install apps instead. 
Also, changing the profile while paused unpauses without updating the notification.

Could you please add an option to show the current profile again and disable the warning?

**Comment by smichel17** [comment]
Hi, thanks for the report. What version of Android are you using? The current profile should be shown, so that sounds like a bug.

The behavior when changing profiles is also a bug, but a separate one; could you split it into its own issue, please?

I'm in the midst of finals right now so I won't be doing any coding for about two weeks, but I'll be back to look into this after that.

**Comment by SZenglein** [comment]
7.1.2

**Comment by smichel17** [comment]
For clarity, this is how it is intended to look: 

![Notification](https://i.imgur.com/UIRA9ID.jpeg]

**Comment by Shookbelf** [comment]
Okay, I now understand what the problem is. I didn't notice the small indicator because it doesn't change when pressing next. 

This is probably the same as #210. I'll update 210 and this issue should be closed

**Comment by SZenglein** [comment]
Okay, I now understand what the problem is. I didn't notice the small indicator because it doesn't change when pressing next.

This is probably the same as #210. I'll update 210 and this issue should be closed
