### ISSUE TITLE
Add More Colors

### ISSUE THREAD

**Issue by IamJithendra** [LibreShift/red-moon#215]
As Like In The Most Color Filter Apps On Google Play Please Provide More Colors and Try To Reduce The App Size

**Comment by smichel17** [comment]
What kind of colors would you like, and why/how would you use them?

**Comment by Jithendra-V-Kumar** [comment]
Please Do Make All Colors Available. The Colors Will Not Be  Alike For All

**Comment by smichel17** [comment]
The purpose of Red Moon is to filter out blue light, to help you fall asleep more easily, and to dim your phone below the maximum, to make it more comfortable to use in a very dark room. So, adding blue as a filter color, for example, works against these goals, and is a feature I will likely not implement.

One key feature of Red Moon is simplicity; I do not want to add any features unless they actually address a someone's real-world use case. I will not add features just because someone might want them. I am much more interested in what color you, @Jithendra-V-Kumar specifically, would like to see.

**Comment by IamJithendra** [comment]
colors Like Black Or Any Other Dark Colors Will Be Helpful

**Comment by smichel17** [comment]
You can get black by turning the intensity down and the dim up, like the default profile, "Dim only".

**Comment by IamJithendra** [comment]
![image](https://user-images.githubusercontent.com/33452200/38821352-e7eff878-41bd-11e8-9ed9-86ce60645601.png)
![image](https://user-images.githubusercontent.com/33452200/38821366-f0945a5a-41bd-11e8-90d9-51d8e845948a.png)
![image](https://user-images.githubusercontent.com/33452200/38821371-f665ab0a-41bd-11e8-920c-1647079938b1.png)

**Comment by IamJithendra** [comment]
@smichel17 Not All The Users Will not like To Change the Dim Light Color By Changing the Temperature Value They like To Click the Color that Like The Most And Because of This Option Not Available on This App Then They Go For A Better App Which Contains this Option

**Comment by IamJithendra** [comment]
@smichel17  Please Have a Look at the Night Mode Applications on Play Store Have The Ability To Change The Colors Of The Screen and Such Apps Have More Downloads And Have High Rating And Can Engage More Users.

**Comment by smichel17** [comment]
The 3 controls already provide some control over the color. If you can say what specific colors you would like and why you want them, I would consider that, but you have not done so (the only color you mentioned is black, which is already possible).

Red Moon already has good reviews (although it can definitely still be better), and I'm not interested in more users for the sake of more users; I'm interested in making Red Moon do its job (helping you get to sleep at night) well.

Finally, please use normal capitalization. the Way You Are Capitalizing is rather hard to read.
