### ISSUE TITLE
System Brightness Integration

### ISSUE THREAD

**Issue by AdamNiederer** [LibreShift/red-moon#220]
Hey,

I use [Lux](https://play.google.com/store/apps/details?id=com.vito.lux) to manage brightness on my AMOLED screen. My favorite part of Lux is its integration with system brightness - setting brightness below 0% activates and sets the overlay, while setting it to a positive number deactivates the overlay and sets system brightness accordingly.

Additionally, it's possible to change brightness from the persistent notification.

Would there be any interest in adding this to red-moon? I could probably lend a hand in implementing the lion's share of these features.

**Comment by smichel17** [comment]
Yes, quite interested. The reason Red Moon doesn't currently work like that is a UX issue: what happens if I use Red Moon to dim below the minimum, but then I use the normal system control to turn the brightness up. How should Red Moon react? How does Lux handle that case?

I'm going to close this in favor of #122, which already has probably-too-much discussion on the topic (feel free to skim instead of reading it all), so let's continue the conversation over there.
