### ISSUE TITLE
Gamma or other blend mode instead of plain alpha blending

### ISSUE THREAD

**Issue by danuker** [LibreShift/red-moon#223]
Hi!

I started using your app, and I think using the filter makes the screen lose a lot of contrast.

I usually use this desktop app, and the text is much easier to read: 
* http://jonls.dk/redshift/
* https://github.com/jonls/redshift/releases

Apparently, they use "gamma ramps" to color the screen (instead of plain linear mixing the screen with the color like you seem to do). This leads to the blacks remaining deep black, and white becoming the color with the proper temperature instead.

They document the choice of color ramp here: 

https://github.com/jonls/redshift/blob/master/README-colorramp

Preview (split screen) from the [website](http://jonls.dk/redshift/):

![screenshot1](http://jonls.dk/assets/screenshot1.png)

**Comment by smichel17** [comment]
It has to do with the method of dimming: Red Moon puts a partially transparent overlay over the entire screen. It's only possible to do gamma ramping on Android if you have root access, since it requires access to the compositor. There's some work in progress to allow using that method on rooted phones. That's tracked in #20; I'm going to close this as a duplicate. Thank you for the link for how redshift does color ramp, which will be helpful once the other backend is in place.
