### ISSUE TITLE
Red Moon does not stay active in the notification tray on Oreo

### ISSUE THREAD

**Issue by jazir555** [LibreShift/red-moon#234]
On 8.0, LG G7+. The filter disappears when I open the tray, and immediately reappears when the tray is closed. I hope there is a way to implement a fix.

**Comment by smichel17** [comment]
Note that Oreo isn't officially supported, see #169

**Comment by AdamNiederer** [comment]
It's unlikely we'll be able to filter the notification tray itself, because of Android-level changes. Is the entire filter disappearing (i.e. under the tray), or just in places where the notification tray is drawn? We may be able to help the former, but the latter is out of our hands, unfortunately.

You can read more about this change here: https://www.xda-developers.com/android-o-is-breaking-apps-that-overlay-on-top-of-the-status-bar/

**Comment by jazir5** [comment]
The former, the entire filter disappears
