### ISSUE TITLE
Introduce the app as an accessibility app

### ISSUE THREAD

**Issue by 0xRustlang** [LibreShift/red-moon#253]
Hello

Thank you for this great app.
i had an feature request that somehow in related to #192 

Please introduce the Red Moon as an Accessibility app to the system.

Why this is important?
Because with this option, when user turns on the accessibility service of red moon in the android setting, Red Moon won't get killed when memory is low.

when using some memory intensive apps most of phones will have memory issue specially middle-range and low-end ones.

for my own this happened very much and it really made my eyes pain.

Please add it if may.

in the past clipstack app used same way.
although duo to Google Play policy, you may cannot put this in your main app (however i don't know the whole policy) but please at least put this option as a external plugin or such may be through F-droid or other means, it will be really helpful)

(if i remember correctly KeePass2Android used some method like this (plugin) after Google Play forced them to remove their accessibility service.)

Thanks.

**Comment by user8446** [comment]
Why don't you turn off battery optimization (Doze) for Red Moon instead? 
Accessibly services is known to slow down your phone: https://www.xda-developers.com/working-as-intended-an-exploration-into-androids-accessibility-lag/

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

Thanks for this useful informations.
The devices i have for example are nexus 9 and j1 ace.
The j1 ace don't have any battery optimization settings as it fortunately have very low amount of bloatware and annoying settings like that (in opposite to huawei/ or doze of marshmallow) and the app will get kill by system because of low amount of ram when using memory intensive apps like browser or... 

Also my nexus 9 have marshmallow and i did whitelisted redmoon in doze settings but because it have 2 GB RAM, the app also get killed by its systems when using memory intensive apps.

As this can occur frequently in low end devices and even sometimes in high-end ones (as described well in dontkillmyapp.com) 

This problem is really annoying specially as this hurts eyes

About lag in accessibility, i didn't noticed it, may be because the app that i used don't read content of screen ( "clipstack" app) and use it only as a way so android don't kill it)

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

Thanks for this useful informations.
The devices i have for example are nexus 9 and j1 ace.
The j1 ace don't have any battery optimization settings as it fortunately have very low amount of bloatware and annoying settings like that (in opposite to huawei/ or doze of marshmallow) and the app will get kill by system because of low amount of ram when using memory intensive apps like browser or... 

Also my nexus 9 have marshmallow and i did whitelisted redmoon in doze settings but because it have 2 GB RAM, the app also get killed by its systems when using memory intensive apps.

As this can occur frequently in low end devices and even sometimes in high-end ones (as described well in dontkillmyapp.com) 

This problem is really annoying specially as this hurts eyes

About lag in accessibility, i didn't noticed it, may be because the app that i used don't read content of screen ( "clipstack" app) and use it only as a way so android don't kill it)

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

Thanks for this useful informations.
The devices i have for example are nexus 9 and j1 ace.
The j1 ace don't have any battery optimization settings as it fortunately have very low amount of bloatware and annoying settings like that (in opposite to huawei/ or doze of marshmallow) and the app will get kill by system because of low amount of ram when using memory intensive apps like browser or... 

Also my nexus 9 have marshmallow and i did whitelisted redmoon in doze settings but because it have 2 GB RAM, the app also get killed by its systems when using memory intensive apps.

As this can occur frequently in low end devices and even sometimes in high-end ones (as described well in dontkillmyapp.com) 

This problem is really annoying specially as this hurts eyes

About lag in accessibility, i didn't noticed it, may be because the app that i used don't read content of screen ( "clipstack" app) and use it only as a way so android don't kill it)

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

Thanks for this useful informations.
The devices i have for example are nexus 9 and j1 ace.
The j1 ace don't have any battery optimization settings as it fortunately have very low amount of bloatware and annoying settings like that (in opposite to huawei/ or doze of marshmallow) and the app will get kill by system because of low amount of ram when using memory intensive apps like browser or... 

Also my nexus 9 have marshmallow and i did whitelisted redmoon in doze settings but because it have 2 GB RAM, the app also get killed by its systems when using memory intensive apps.

As this can occur frequently in low end devices and even sometimes in high-end ones (as described well in dontkillmyapp.com) 

This problem is really annoying specially as this hurts eyes

About lag in accessibility, i didn't noticed it, may be because the app that i used don't read content of screen ( "clipstack" app) and use it only as a way so android don't kill it)

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello

Thanks for this useful informations.
The devices i have for example are nexus 9 and j1 ace.
The j1 ace don't have any battery optimization settings as it fortunately have very low amount of bloatware and annoying settings like that (in opposite to huawei/ or doze of marshmallow) and the app will get kill by system because of low amount of ram when using memory intensive apps like browser or... 

Also my nexus 9 have marshmallow and i did whitelisted redmoon in doze settings but because it have 2 GB RAM, the app also get killed by its systems when using memory intensive apps.

As this can occur frequently in low end devices and even sometimes in high-end ones (as described well in dontkillmyapp.com) 

This problem is really annoying specially as this hurts eyes

About lag in accessibility, i didn't noticed it, may be because the app that i used don't read content of screen ( "clipstack" app) and use it only as a way so android don't kill it)

**Comment by goombapatrol** [comment]
**+1** This is much needed. epileptic and very sensitive to blue light, this app is the only way I can use device.

Red moon gets killed sporadically on my G Pad 7 (low-end) even when doing relatively non-intensive tasks. With notification gone, I have to minimize everything i'm doing to toggle again (with eyes half covered).
I see no doze setting on my tablet (Android 5.0.2), and don't have any other 'battery saver' apps enabled.

I will gladly tolerate any slowdown or other compromises that it may take to prevent abrupt closing.

**Comment by smichel17** [comment]
I will consider it.

It's frustrating because this is *entirely* the manufacturer's fault. Red Moon already tells the OS "I'm in use, don't kill me!" Yet manufacturers continue to put features in that make it hard for apps to work. (In fairness, I suppose this is partially in response to developers running their apps when they don't need to be running).

**Comment by user8446** [comment]
That tablet only has 1gb of RAM, you're maxing out probably with just the OS, browser, keyboard, etc. Look to see in settings > battery if there is "battery optimization" where you selectively choose for each app.

**Comment by smichel17** [comment]
I would not have the accessibility service option enabled by default, and would clearly label that it can slow down the phone and is only for people who are experiencing problems with Red Moon getting killed.

Also, I would be interested in seeing if there's any way to reduce our own memory footprint. I'm pretty sure most of it boils down to "X red pixels", but I also haven't done any profiling to confirm that suspicion.

**Comment by goombapatrol** [comment]
Unfortunately, I see no settings > battery related to per-app. Just a list of charge history, remaining time, and checkbox to warn and dim at 15%. 1GB isn't large, but everything else I use it for performs fine within that constraint. (I don't need any other apps aside from Red Moon kept running in background, not multitasking).

Thanks for consideration.

**Comment by NoahAndrews** [comment]
Look under apps ->  Special App Access

**Comment by goombapatrol** [comment]
I see lists of "On SD Card, Downloaded, Running, All", no Special App Access. That must be a newer feature?

**Comment by 3j9fkyahunqoxwqu** [comment]
@goombapatrol 
Yes, your device has lolipop, the battery optimization and special access that i think introduced with permission controls are for devices running marshmallow and later versions.

@smichel17 
Thank you very much
It will be really great.
Really thank you :)

**Comment by matteocoder** [comment]
Running Red Moon as an accessibility app will also allow it to filter things like the notification shade and Moto Display on Oreo and above. This is what Twilight's developer recently did.
