### ISSUE TITLE
red-moon (filter) not applied for notifications and lock screen in android 8

### ISSUE THREAD

**Issue by sathvik12345** [LibreShift/red-moon#254]

**Comment by AdamNiederer** [comment]
This is expected behavior, unfortunately. Android Oreo disallows applications from drawing over the notification shade, status bar, lockscreen, and other "system-level" windows, and there isn't much we can do about it programmatically.

https://www.xda-developers.com/android-o-is-breaking-apps-that-overlay-on-top-of-the-status-bar/
