### ISSUE TITLE
RedMond: GPS Location

### ISSUE THREAD

**Issue by falkpaulfabian2004** [LibreShift/red-moon#328]
For what needs red moon GPS location?

**Comment by smichel17** [comment]
Sunrise and sunset times are calculated based on your location. This does not need to be precise (gps); approximate (network) location works fine. We added support for gps location due to a feature request from someone whose device had gps but did not support network location: #107

In the implementation, we first check if network location is available, and use that if it is; we only use gps location if network is not available. Here's the code: https://github.com/LibreShift/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/service/LocationUpdateService.kt#L121
